### ISSUE TITLE
error while npm install

### ISSUE THREAD

**Issue by Somebi** [anandsuresh/sse4_crc32#63]
```
505 verbose If you need help, you may report this error at:
505 verbose     <https://github.com/npm/npm/issues>
506 warn bot@1.0.0 No repository field.
507 verbose If you need help, you may report this error at:
507 verbose     <https://github.com/npm/npm/issues>
508 verbose stack Error: sse4_crc32@5.1.1 install: `node-gyp rebuild`
508 verbose stack Exit status 1
508 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
508 verbose stack     at emitTwo (events.js:106:13)
508 verbose stack     at EventEmitter.emit (events.js:192:7)
508 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
508 verbose stack     at emitTwo (events.js:106:13)
508 verbose stack     at ChildProcess.emit (events.js:192:7)
508 verbose stack     at maybeClose (internal/child_process.js:890:16)
508 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
509 verbose pkgid sse4_crc32@5.1.1
510 verbose cwd /var/local/bot
511 error Linux 4.4.0-62-generic
512 error argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "--no-bin-links" "sse4_crc32"
513 error node v7.5.0
514 error npm  v4.1.2
515 error code ELIFECYCLE
516 error sse4_crc32@5.1.1 install: `node-gyp rebuild`
516 error Exit status 1
517 error Failed at the sse4_crc32@5.1.1 install script 'node-gyp rebuild'.
517 error Make sure you have the latest version of node.js and npm installed.
517 error If you do, this is most likely a problem with the sse4_crc32 package,
517 error not with npm itself.
517 error Tell the author that this fails on your system:
517 error     node-gyp rebuild
517 error You can get information on how to open an issue for this project with:
517 error     npm bugs sse4_crc32
517 error Or if that isn't available, you can get their info via:
517 error     npm owner ls sse4_crc32
517 error There is likely additional logging output above.
518 verbose exit [ 1, true ]

```

**Comment by anandsuresh** [comment]
Can you run the npm install with debug and post logs please?

**Comment by Somebi** [comment]
Sure, here you go. Will that be enough?

http://pastebin.com/3VK3G0EG

**Comment by Somebi** [comment]
Btw i'm installing it inside docker container with Ubuntu 14.04 inside it.

**Comment by anandsuresh** [comment]
Seems like you're missing g++ on the compile path.

``` bash
make: Entering directory `/tmp/node_modules/sse4_crc32/build'
  g++ '-DNODE_GYP_MODULE_NAME=crc32c_sse42' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DNDEBUG' -I/root/.node-gyp/7.5.0/include/node -I/root/.node-gyp/7.5.0/src -I/root/.node-gyp/7.5.0/deps/uv/include -I/root/.node-gyp/7.5.0/deps/v8/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -msse4.2 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++0x -MMD -MF ./Release/.deps/Release/obj.target/crc32c_sse42/src/crc32c_sse42.o.d.raw   -c -o Release/obj.target/crc32c_sse42/src/crc32c_sse42.o ../src/crc32c_sse42.cpp
make: g++: Command not found
make: *** [Release/obj.target/crc32c_sse42/src/crc32c_sse42.o] Error 127
make: Leaving directory `/tmp/node_modules/sse4_crc32/build'
```

**Comment by anandsuresh** [comment]
I'm going to close this out. Feel free to re-open if the problem persists.

**Comment by Somebi** [comment]
Add it to deps list.
