### ISSUE TITLE
Benchmark fails to run on Node.js 12.11.1

### ISSUE THREAD

**Issue by gabrielschulhof** [anandsuresh/sse4_crc32#77]
```
single fixed-size buffer, 10000 iterations:
- Native SSE 4.2 CRC-32C: 3.038184 ms
- Native Table-based CRC-32C: 7.241885 ms
- JavaScript (table-based) CRC-32C: 51.763529 ms
- JavaScript (direct) CRC-32C: 256.636801 ms


internal/validators.js:83
        throw new ERR_OUT_OF_RANGE(name, 'an integer', value);
        ^

RangeError [ERR_OUT_OF_RANGE]: The value of "length" is out of range. It must be an integer. Received 8.320986338119837
    at Buffer.write (buffer.js:1017:7)
    at Object.initBuffers [as init] (/home/nix/node/sse4_crc32/benchmark/multiple_random_size_buffers.benchmark.js:35:11)
    at /home/nix/node/sse4_crc32/benchmark/index.js:33:15
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (/home/nix/node/sse4_crc32/benchmark/index.js:30:3)
    at Module._compile (internal/modules/cjs/loader.js:945:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1014:10)
```

At first blush it looks like it might need a `Math.round()`.

**Comment by anandsuresh** [comment]
Yup. Just got a fix in. Thanks for catching this and reporting it.
