### ISSUE TITLE
Failed to load in Docker env

### ISSUE THREAD

**Issue by chulanovskyi-bs** [anandsuresh/sse4_crc32#79]
Hi!

I'm using Docker on my macOs Catalina 10.15.4 and the issue is firing just if the `sse4_crc32` lib is imported (not even called):

```
Using ts-node version 8.8.2, typescript version 3.8.2
Error: Error loading shared library /app/node_modules/sse4_crc32/build/Release/crc32c.node: Exec format error
    at Module._extensions..node (internal/modules/cjs/loader.js:1208:18)
    at Object.nodeDevHook [as .node] (/app/node_modules/ts-node-dev/lib/hook.js:61:7)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/app/node_modules/sse4_crc32/index.js:9:35)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Module._compile (/app/node_modules/source-map-support/source-map-support.js:541:25)
[ERROR] 01:46:55 Error: Error loading shared library /app/node_modules/sse4_crc32/build/Release/crc32c.node: Exec format error
```

The `dockerfile` as following:

```
FROM node:12.16.1-alpine

WORKDIR /app

COPY ./package.json ./

# support compiling for sse4_crc32 module
RUN apk --no-cache --virtual build-dependencies add \
  python \
  make \
  g++ \
  libbz2 \
  && npm install \
  && apk del build-dependencies

CMD npm run dev
```

If I use local env (regular, without docker) - everything works without an error. I've also tried other `node` docker images, like `mhart/alpine-node`, but it doesn't helped.

**Comment by anandsuresh** [comment]
Need more detailed logs to figure this out. On the face of it, the `Exec format error` is usually indicative of the fact that the compiled binary (crc32c.node) is not built for the target architecture you are running on. It is also possible that this is specific to docker on MacOS.

**Comment by chulanovskyi-bs** [comment]
> Need more detailed logs to figure this out.

Ok, how can I help with this? Is there any 'debug' mode for installation?

**Comment by anandsuresh** [comment]
A good starting point would be the full logs from the run.

**Comment by anandsuresh** [comment]
Also, version numbers of the key components would be helpful.

**Comment by chulanovskyi-bs** [comment]
Sure, here is what I've prepared:
* Minimum reproduced repo: [link](https://github.com/chulanovskyi-bs/mvp)
* The logs from the _outside_ docker env run: [link](https://gist.github.com/chulanovskyi-bs/39f5bc593c8e428703a8ee2311db44bd)
* The logs from the docker env run: [link](https://gist.github.com/chulanovskyi-bs/543f56e5735ef12d108d07f5c2cb885a)

**Comment by anandsuresh** [comment]
Can you confirm the C/C++ compiler you are using outside of docker?

**Comment by chulanovskyi-bs** [comment]
Did not perform any specific (dedicated) installations of the compiler. I guess it is default that comes with the OS

How do I check it?

**Comment by Brooooooklyn** [comment]
try [@node-rs/crc32](https://github.com/napi-rs/node-rs/tree/master/packages/crc32)
